repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      # - id: pretty-format-yaml
      #   args: [--autofix, --indent, "2"]
      - id: pretty-format-toml
        args: [--autofix, --indent, "2"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
